version: '3.4'
services:
    php:
        build: ./docker
        image: php74
        restart: on-failure
        ports:
            - ${APP_PORT}
        environment:
          APP_PORT: ${APP_PORT}
        volumes:
            - ".:/var/www/html"
volumes:
  php:
